#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS1_QLPKB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DoAnQLPK")]
	public partial class LINQ1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBacSi(BacSi instance);
    partial void UpdateBacSi(BacSi instance);
    partial void DeleteBacSi(BacSi instance);
    partial void InsertBenh(Benh instance);
    partial void UpdateBenh(Benh instance);
    partial void DeleteBenh(Benh instance);
    partial void InsertBenhAn(BenhAn instance);
    partial void UpdateBenhAn(BenhAn instance);
    partial void DeleteBenhAn(BenhAn instance);
    partial void InsertBenhNhan(BenhNhan instance);
    partial void UpdateBenhNhan(BenhNhan instance);
    partial void DeleteBenhNhan(BenhNhan instance);
    partial void InsertDanhSachBenhNhan(DanhSachBenhNhan instance);
    partial void UpdateDanhSachBenhNhan(DanhSachBenhNhan instance);
    partial void DeleteDanhSachBenhNhan(DanhSachBenhNhan instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertThuoc(Thuoc instance);
    partial void UpdateThuoc(Thuoc instance);
    partial void DeleteThuoc(Thuoc instance);
    partial void InsertThuocBenhNhan(ThuocBenhNhan instance);
    partial void UpdateThuocBenhNhan(ThuocBenhNhan instance);
    partial void DeleteThuocBenhNhan(ThuocBenhNhan instance);
    partial void InsertToaThuoc(ToaThuoc instance);
    partial void UpdateToaThuoc(ToaThuoc instance);
    partial void DeleteToaThuoc(ToaThuoc instance);
    #endregion
		
		public LINQ1DataContext() : 
				base(global::DACS1_QLPKB.Properties.Settings.Default.DoAnQLPKConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BacSi> BacSis
		{
			get
			{
				return this.GetTable<BacSi>();
			}
		}
		
		public System.Data.Linq.Table<Benh> Benhs
		{
			get
			{
				return this.GetTable<Benh>();
			}
		}
		
		public System.Data.Linq.Table<BenhAn> BenhAns
		{
			get
			{
				return this.GetTable<BenhAn>();
			}
		}
		
		public System.Data.Linq.Table<BenhNhan> BenhNhans
		{
			get
			{
				return this.GetTable<BenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachBenhNhan> DanhSachBenhNhans
		{
			get
			{
				return this.GetTable<DanhSachBenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<HeThong> HeThongs
		{
			get
			{
				return this.GetTable<HeThong>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<Thuoc> Thuocs
		{
			get
			{
				return this.GetTable<Thuoc>();
			}
		}
		
		public System.Data.Linq.Table<ThuocBenhNhan> ThuocBenhNhans
		{
			get
			{
				return this.GetTable<ThuocBenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<ToaThuoc> ToaThuocs
		{
			get
			{
				return this.GetTable<ToaThuoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BacSi")]
	public partial class BacSi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDbs;
		
		private string _Tenbs;
		
		private string _SDTbs;
		
		private string _Diachibs;
		
		private string _Taikhoan;
		
		private string _MatKhau;
		
		private EntitySet<DanhSachBenhNhan> _DanhSachBenhNhans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDbsChanging(int value);
    partial void OnIDbsChanged();
    partial void OnTenbsChanging(string value);
    partial void OnTenbsChanged();
    partial void OnSDTbsChanging(string value);
    partial void OnSDTbsChanged();
    partial void OnDiachibsChanging(string value);
    partial void OnDiachibsChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public BacSi()
		{
			this._DanhSachBenhNhans = new EntitySet<DanhSachBenhNhan>(new Action<DanhSachBenhNhan>(this.attach_DanhSachBenhNhans), new Action<DanhSachBenhNhan>(this.detach_DanhSachBenhNhans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbs", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDbs
		{
			get
			{
				return this._IDbs;
			}
			set
			{
				if ((this._IDbs != value))
				{
					this.OnIDbsChanging(value);
					this.SendPropertyChanging();
					this._IDbs = value;
					this.SendPropertyChanged("IDbs");
					this.OnIDbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenbs", DbType="NVarChar(50)")]
		public string Tenbs
		{
			get
			{
				return this._Tenbs;
			}
			set
			{
				if ((this._Tenbs != value))
				{
					this.OnTenbsChanging(value);
					this.SendPropertyChanging();
					this._Tenbs = value;
					this.SendPropertyChanged("Tenbs");
					this.OnTenbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTbs", DbType="NVarChar(50)")]
		public string SDTbs
		{
			get
			{
				return this._SDTbs;
			}
			set
			{
				if ((this._SDTbs != value))
				{
					this.OnSDTbsChanging(value);
					this.SendPropertyChanging();
					this._SDTbs = value;
					this.SendPropertyChanged("SDTbs");
					this.OnSDTbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachibs", DbType="NVarChar(50)")]
		public string Diachibs
		{
			get
			{
				return this._Diachibs;
			}
			set
			{
				if ((this._Diachibs != value))
				{
					this.OnDiachibsChanging(value);
					this.SendPropertyChanging();
					this._Diachibs = value;
					this.SendPropertyChanged("Diachibs");
					this.OnDiachibsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="NVarChar(50)")]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BacSi_DanhSachBenhNhan", Storage="_DanhSachBenhNhans", ThisKey="IDbs", OtherKey="IDbs")]
		public EntitySet<DanhSachBenhNhan> DanhSachBenhNhans
		{
			get
			{
				return this._DanhSachBenhNhans;
			}
			set
			{
				this._DanhSachBenhNhans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhSachBenhNhans(DanhSachBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.BacSi = this;
		}
		
		private void detach_DanhSachBenhNhans(DanhSachBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.BacSi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Benh")]
	public partial class Benh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDbenh;
		
		private string _Tenbenh;
		
		private EntitySet<DanhSachBenhNhan> _DanhSachBenhNhans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDbenhChanging(int value);
    partial void OnIDbenhChanged();
    partial void OnTenbenhChanging(string value);
    partial void OnTenbenhChanged();
    #endregion
		
		public Benh()
		{
			this._DanhSachBenhNhans = new EntitySet<DanhSachBenhNhan>(new Action<DanhSachBenhNhan>(this.attach_DanhSachBenhNhans), new Action<DanhSachBenhNhan>(this.detach_DanhSachBenhNhans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbenh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDbenh
		{
			get
			{
				return this._IDbenh;
			}
			set
			{
				if ((this._IDbenh != value))
				{
					this.OnIDbenhChanging(value);
					this.SendPropertyChanging();
					this._IDbenh = value;
					this.SendPropertyChanged("IDbenh");
					this.OnIDbenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenbenh", DbType="NVarChar(50)")]
		public string Tenbenh
		{
			get
			{
				return this._Tenbenh;
			}
			set
			{
				if ((this._Tenbenh != value))
				{
					this.OnTenbenhChanging(value);
					this.SendPropertyChanging();
					this._Tenbenh = value;
					this.SendPropertyChanged("Tenbenh");
					this.OnTenbenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Benh_DanhSachBenhNhan", Storage="_DanhSachBenhNhans", ThisKey="IDbenh", OtherKey="IDbenh")]
		public EntitySet<DanhSachBenhNhan> DanhSachBenhNhans
		{
			get
			{
				return this._DanhSachBenhNhans;
			}
			set
			{
				this._DanhSachBenhNhans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhSachBenhNhans(DanhSachBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.Benh1 = this;
		}
		
		private void detach_DanhSachBenhNhans(DanhSachBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.Benh1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BenhAn")]
	public partial class BenhAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDban;
		
		private System.Nullable<int> _IDtoa;
		
		private string _Tenbn;
		
		private string _SDTbn;
		
		private string _Benh;
		
		private EntityRef<ToaThuoc> _ToaThuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDbanChanging(int value);
    partial void OnIDbanChanged();
    partial void OnIDtoaChanging(System.Nullable<int> value);
    partial void OnIDtoaChanged();
    partial void OnTenbnChanging(string value);
    partial void OnTenbnChanged();
    partial void OnSDTbnChanging(string value);
    partial void OnSDTbnChanged();
    partial void OnBenhChanging(string value);
    partial void OnBenhChanged();
    #endregion
		
		public BenhAn()
		{
			this._ToaThuoc = default(EntityRef<ToaThuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDban", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDban
		{
			get
			{
				return this._IDban;
			}
			set
			{
				if ((this._IDban != value))
				{
					this.OnIDbanChanging(value);
					this.SendPropertyChanging();
					this._IDban = value;
					this.SendPropertyChanged("IDban");
					this.OnIDbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDtoa", DbType="Int")]
		public System.Nullable<int> IDtoa
		{
			get
			{
				return this._IDtoa;
			}
			set
			{
				if ((this._IDtoa != value))
				{
					if (this._ToaThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDtoaChanging(value);
					this.SendPropertyChanging();
					this._IDtoa = value;
					this.SendPropertyChanged("IDtoa");
					this.OnIDtoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenbn", DbType="NVarChar(50)")]
		public string Tenbn
		{
			get
			{
				return this._Tenbn;
			}
			set
			{
				if ((this._Tenbn != value))
				{
					this.OnTenbnChanging(value);
					this.SendPropertyChanging();
					this._Tenbn = value;
					this.SendPropertyChanged("Tenbn");
					this.OnTenbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTbn", DbType="NVarChar(50)")]
		public string SDTbn
		{
			get
			{
				return this._SDTbn;
			}
			set
			{
				if ((this._SDTbn != value))
				{
					this.OnSDTbnChanging(value);
					this.SendPropertyChanging();
					this._SDTbn = value;
					this.SendPropertyChanged("SDTbn");
					this.OnSDTbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Benh", DbType="NVarChar(50)")]
		public string Benh
		{
			get
			{
				return this._Benh;
			}
			set
			{
				if ((this._Benh != value))
				{
					this.OnBenhChanging(value);
					this.SendPropertyChanging();
					this._Benh = value;
					this.SendPropertyChanged("Benh");
					this.OnBenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ToaThuoc_BenhAn", Storage="_ToaThuoc", ThisKey="IDtoa", OtherKey="IDtoa", IsForeignKey=true)]
		public ToaThuoc ToaThuoc
		{
			get
			{
				return this._ToaThuoc.Entity;
			}
			set
			{
				ToaThuoc previousValue = this._ToaThuoc.Entity;
				if (((previousValue != value) 
							|| (this._ToaThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ToaThuoc.Entity = null;
						previousValue.BenhAns.Remove(this);
					}
					this._ToaThuoc.Entity = value;
					if ((value != null))
					{
						value.BenhAns.Add(this);
						this._IDtoa = value.IDtoa;
					}
					else
					{
						this._IDtoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("ToaThuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BenhNhan")]
	public partial class BenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDbn;
		
		private string _Tenbn;
		
		private string _SDTbn;
		
		private string _Diachibn;
		
		private string _Gioitinh;
		
		private string _Trieuchung;
		
		private System.Nullable<int> _IDnv;
		
		private EntitySet<DanhSachBenhNhan> _DanhSachBenhNhans;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDbnChanging(int value);
    partial void OnIDbnChanged();
    partial void OnTenbnChanging(string value);
    partial void OnTenbnChanged();
    partial void OnSDTbnChanging(string value);
    partial void OnSDTbnChanged();
    partial void OnDiachibnChanging(string value);
    partial void OnDiachibnChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnTrieuchungChanging(string value);
    partial void OnTrieuchungChanged();
    partial void OnIDnvChanging(System.Nullable<int> value);
    partial void OnIDnvChanged();
    #endregion
		
		public BenhNhan()
		{
			this._DanhSachBenhNhans = new EntitySet<DanhSachBenhNhan>(new Action<DanhSachBenhNhan>(this.attach_DanhSachBenhNhans), new Action<DanhSachBenhNhan>(this.detach_DanhSachBenhNhans));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDbn
		{
			get
			{
				return this._IDbn;
			}
			set
			{
				if ((this._IDbn != value))
				{
					this.OnIDbnChanging(value);
					this.SendPropertyChanging();
					this._IDbn = value;
					this.SendPropertyChanged("IDbn");
					this.OnIDbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenbn", DbType="NVarChar(50)")]
		public string Tenbn
		{
			get
			{
				return this._Tenbn;
			}
			set
			{
				if ((this._Tenbn != value))
				{
					this.OnTenbnChanging(value);
					this.SendPropertyChanging();
					this._Tenbn = value;
					this.SendPropertyChanged("Tenbn");
					this.OnTenbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTbn", DbType="NVarChar(50)")]
		public string SDTbn
		{
			get
			{
				return this._SDTbn;
			}
			set
			{
				if ((this._SDTbn != value))
				{
					this.OnSDTbnChanging(value);
					this.SendPropertyChanging();
					this._SDTbn = value;
					this.SendPropertyChanged("SDTbn");
					this.OnSDTbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachibn", DbType="NVarChar(50)")]
		public string Diachibn
		{
			get
			{
				return this._Diachibn;
			}
			set
			{
				if ((this._Diachibn != value))
				{
					this.OnDiachibnChanging(value);
					this.SendPropertyChanging();
					this._Diachibn = value;
					this.SendPropertyChanged("Diachibn");
					this.OnDiachibnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(50)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trieuchung", DbType="NVarChar(50)")]
		public string Trieuchung
		{
			get
			{
				return this._Trieuchung;
			}
			set
			{
				if ((this._Trieuchung != value))
				{
					this.OnTrieuchungChanging(value);
					this.SendPropertyChanging();
					this._Trieuchung = value;
					this.SendPropertyChanged("Trieuchung");
					this.OnTrieuchungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDnv", DbType="Int")]
		public System.Nullable<int> IDnv
		{
			get
			{
				return this._IDnv;
			}
			set
			{
				if ((this._IDnv != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDnvChanging(value);
					this.SendPropertyChanging();
					this._IDnv = value;
					this.SendPropertyChanged("IDnv");
					this.OnIDnvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_DanhSachBenhNhan", Storage="_DanhSachBenhNhans", ThisKey="IDbn", OtherKey="IDbn")]
		public EntitySet<DanhSachBenhNhan> DanhSachBenhNhans
		{
			get
			{
				return this._DanhSachBenhNhans;
			}
			set
			{
				this._DanhSachBenhNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BenhNhan", Storage="_NhanVien", ThisKey="IDnv", OtherKey="IDnv", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.BenhNhans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.BenhNhans.Add(this);
						this._IDnv = value.IDnv;
					}
					else
					{
						this._IDnv = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhSachBenhNhans(DanhSachBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = this;
		}
		
		private void detach_DanhSachBenhNhans(DanhSachBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachBenhNhan")]
	public partial class DanhSachBenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDdsbn;
		
		private System.Nullable<int> _IDbn;
		
		private string _Tenbn;
		
		private string _SDTbn;
		
		private string _Benh;
		
		private string _Trieuchung;
		
		private string _BSkham;
		
		private string _Tinhtrang;
		
		private System.Nullable<int> _IDbenh;
		
		private System.Nullable<int> _IDbs;
		
		private EntitySet<ToaThuoc> _ToaThuocs;
		
		private EntityRef<BacSi> _BacSi;
		
		private EntityRef<Benh> _Benh1;
		
		private EntityRef<BenhNhan> _BenhNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDdsbnChanging(int value);
    partial void OnIDdsbnChanged();
    partial void OnIDbnChanging(System.Nullable<int> value);
    partial void OnIDbnChanged();
    partial void OnTenbnChanging(string value);
    partial void OnTenbnChanged();
    partial void OnSDTbnChanging(string value);
    partial void OnSDTbnChanged();
    partial void OnBenhChanging(string value);
    partial void OnBenhChanged();
    partial void OnTrieuchungChanging(string value);
    partial void OnTrieuchungChanged();
    partial void OnBSkhamChanging(string value);
    partial void OnBSkhamChanged();
    partial void OnTinhtrangChanging(string value);
    partial void OnTinhtrangChanged();
    partial void OnIDbenhChanging(System.Nullable<int> value);
    partial void OnIDbenhChanged();
    partial void OnIDbsChanging(System.Nullable<int> value);
    partial void OnIDbsChanged();
    #endregion
		
		public DanhSachBenhNhan()
		{
			this._ToaThuocs = new EntitySet<ToaThuoc>(new Action<ToaThuoc>(this.attach_ToaThuocs), new Action<ToaThuoc>(this.detach_ToaThuocs));
			this._BacSi = default(EntityRef<BacSi>);
			this._Benh1 = default(EntityRef<Benh>);
			this._BenhNhan = default(EntityRef<BenhNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDdsbn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDdsbn
		{
			get
			{
				return this._IDdsbn;
			}
			set
			{
				if ((this._IDdsbn != value))
				{
					this.OnIDdsbnChanging(value);
					this.SendPropertyChanging();
					this._IDdsbn = value;
					this.SendPropertyChanged("IDdsbn");
					this.OnIDdsbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbn", DbType="Int")]
		public System.Nullable<int> IDbn
		{
			get
			{
				return this._IDbn;
			}
			set
			{
				if ((this._IDbn != value))
				{
					if (this._BenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDbnChanging(value);
					this.SendPropertyChanging();
					this._IDbn = value;
					this.SendPropertyChanged("IDbn");
					this.OnIDbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenbn", DbType="NVarChar(50)")]
		public string Tenbn
		{
			get
			{
				return this._Tenbn;
			}
			set
			{
				if ((this._Tenbn != value))
				{
					this.OnTenbnChanging(value);
					this.SendPropertyChanging();
					this._Tenbn = value;
					this.SendPropertyChanged("Tenbn");
					this.OnTenbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTbn", DbType="NVarChar(50)")]
		public string SDTbn
		{
			get
			{
				return this._SDTbn;
			}
			set
			{
				if ((this._SDTbn != value))
				{
					this.OnSDTbnChanging(value);
					this.SendPropertyChanging();
					this._SDTbn = value;
					this.SendPropertyChanged("SDTbn");
					this.OnSDTbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Benh", DbType="NVarChar(50)")]
		public string Benh
		{
			get
			{
				return this._Benh;
			}
			set
			{
				if ((this._Benh != value))
				{
					this.OnBenhChanging(value);
					this.SendPropertyChanging();
					this._Benh = value;
					this.SendPropertyChanged("Benh");
					this.OnBenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trieuchung", DbType="NVarChar(50)")]
		public string Trieuchung
		{
			get
			{
				return this._Trieuchung;
			}
			set
			{
				if ((this._Trieuchung != value))
				{
					this.OnTrieuchungChanging(value);
					this.SendPropertyChanging();
					this._Trieuchung = value;
					this.SendPropertyChanged("Trieuchung");
					this.OnTrieuchungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSkham", DbType="NVarChar(50)")]
		public string BSkham
		{
			get
			{
				return this._BSkham;
			}
			set
			{
				if ((this._BSkham != value))
				{
					this.OnBSkhamChanging(value);
					this.SendPropertyChanging();
					this._BSkham = value;
					this.SendPropertyChanged("BSkham");
					this.OnBSkhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang", DbType="NVarChar(50)")]
		public string Tinhtrang
		{
			get
			{
				return this._Tinhtrang;
			}
			set
			{
				if ((this._Tinhtrang != value))
				{
					this.OnTinhtrangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang = value;
					this.SendPropertyChanged("Tinhtrang");
					this.OnTinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbenh", DbType="Int")]
		public System.Nullable<int> IDbenh
		{
			get
			{
				return this._IDbenh;
			}
			set
			{
				if ((this._IDbenh != value))
				{
					if (this._Benh1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDbenhChanging(value);
					this.SendPropertyChanging();
					this._IDbenh = value;
					this.SendPropertyChanged("IDbenh");
					this.OnIDbenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbs", DbType="Int")]
		public System.Nullable<int> IDbs
		{
			get
			{
				return this._IDbs;
			}
			set
			{
				if ((this._IDbs != value))
				{
					if (this._BacSi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDbsChanging(value);
					this.SendPropertyChanging();
					this._IDbs = value;
					this.SendPropertyChanged("IDbs");
					this.OnIDbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachBenhNhan_ToaThuoc", Storage="_ToaThuocs", ThisKey="IDdsbn", OtherKey="IDdsbn")]
		public EntitySet<ToaThuoc> ToaThuocs
		{
			get
			{
				return this._ToaThuocs;
			}
			set
			{
				this._ToaThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BacSi_DanhSachBenhNhan", Storage="_BacSi", ThisKey="IDbs", OtherKey="IDbs", IsForeignKey=true)]
		public BacSi BacSi
		{
			get
			{
				return this._BacSi.Entity;
			}
			set
			{
				BacSi previousValue = this._BacSi.Entity;
				if (((previousValue != value) 
							|| (this._BacSi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BacSi.Entity = null;
						previousValue.DanhSachBenhNhans.Remove(this);
					}
					this._BacSi.Entity = value;
					if ((value != null))
					{
						value.DanhSachBenhNhans.Add(this);
						this._IDbs = value.IDbs;
					}
					else
					{
						this._IDbs = default(Nullable<int>);
					}
					this.SendPropertyChanged("BacSi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Benh_DanhSachBenhNhan", Storage="_Benh1", ThisKey="IDbenh", OtherKey="IDbenh", IsForeignKey=true)]
		public Benh Benh1
		{
			get
			{
				return this._Benh1.Entity;
			}
			set
			{
				Benh previousValue = this._Benh1.Entity;
				if (((previousValue != value) 
							|| (this._Benh1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Benh1.Entity = null;
						previousValue.DanhSachBenhNhans.Remove(this);
					}
					this._Benh1.Entity = value;
					if ((value != null))
					{
						value.DanhSachBenhNhans.Add(this);
						this._IDbenh = value.IDbenh;
					}
					else
					{
						this._IDbenh = default(Nullable<int>);
					}
					this.SendPropertyChanged("Benh1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_DanhSachBenhNhan", Storage="_BenhNhan", ThisKey="IDbn", OtherKey="IDbn", IsForeignKey=true)]
		public BenhNhan BenhNhan
		{
			get
			{
				return this._BenhNhan.Entity;
			}
			set
			{
				BenhNhan previousValue = this._BenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhan.Entity = null;
						previousValue.DanhSachBenhNhans.Remove(this);
					}
					this._BenhNhan.Entity = value;
					if ((value != null))
					{
						value.DanhSachBenhNhans.Add(this);
						this._IDbn = value.IDbn;
					}
					else
					{
						this._IDbn = default(Nullable<int>);
					}
					this.SendPropertyChanged("BenhNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ToaThuocs(ToaThuoc entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachBenhNhan = this;
		}
		
		private void detach_ToaThuocs(ToaThuoc entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachBenhNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HeThong")]
	public partial class HeThong
	{
		
		private string _Tenht;
		
		private string _SDT;
		
		private string _Diachi;
		
		private string _DiachiEmail;
		
		private string _Giolam;
		
		public HeThong()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenht", DbType="NVarChar(50)")]
		public string Tenht
		{
			get
			{
				return this._Tenht;
			}
			set
			{
				if ((this._Tenht != value))
				{
					this._Tenht = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this._Diachi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiachiEmail", DbType="NVarChar(50)")]
		public string DiachiEmail
		{
			get
			{
				return this._DiachiEmail;
			}
			set
			{
				if ((this._DiachiEmail != value))
				{
					this._DiachiEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giolam", DbType="NVarChar(50)")]
		public string Giolam
		{
			get
			{
				return this._Giolam;
			}
			set
			{
				if ((this._Giolam != value))
				{
					this._Giolam = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDhd;
		
		private System.Nullable<int> _IDtoa;
		
		private string _Tenbn;
		
		private string _SDTbn;
		
		private string _BSkham;
		
		private System.Nullable<double> _Tongtien;
		
		private System.Nullable<System.DateTime> _Ngaykham;
		
		private EntityRef<ToaThuoc> _ToaThuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDhdChanging(int value);
    partial void OnIDhdChanged();
    partial void OnIDtoaChanging(System.Nullable<int> value);
    partial void OnIDtoaChanged();
    partial void OnTenbnChanging(string value);
    partial void OnTenbnChanged();
    partial void OnSDTbnChanging(string value);
    partial void OnSDTbnChanged();
    partial void OnBSkhamChanging(string value);
    partial void OnBSkhamChanged();
    partial void OnTongtienChanging(System.Nullable<double> value);
    partial void OnTongtienChanged();
    partial void OnNgaykhamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaykhamChanged();
    #endregion
		
		public HoaDon()
		{
			this._ToaThuoc = default(EntityRef<ToaThuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDhd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDhd
		{
			get
			{
				return this._IDhd;
			}
			set
			{
				if ((this._IDhd != value))
				{
					this.OnIDhdChanging(value);
					this.SendPropertyChanging();
					this._IDhd = value;
					this.SendPropertyChanged("IDhd");
					this.OnIDhdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDtoa", DbType="Int")]
		public System.Nullable<int> IDtoa
		{
			get
			{
				return this._IDtoa;
			}
			set
			{
				if ((this._IDtoa != value))
				{
					if (this._ToaThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDtoaChanging(value);
					this.SendPropertyChanging();
					this._IDtoa = value;
					this.SendPropertyChanged("IDtoa");
					this.OnIDtoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenbn", DbType="NVarChar(50)")]
		public string Tenbn
		{
			get
			{
				return this._Tenbn;
			}
			set
			{
				if ((this._Tenbn != value))
				{
					this.OnTenbnChanging(value);
					this.SendPropertyChanging();
					this._Tenbn = value;
					this.SendPropertyChanged("Tenbn");
					this.OnTenbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTbn", DbType="NVarChar(50)")]
		public string SDTbn
		{
			get
			{
				return this._SDTbn;
			}
			set
			{
				if ((this._SDTbn != value))
				{
					this.OnSDTbnChanging(value);
					this.SendPropertyChanging();
					this._SDTbn = value;
					this.SendPropertyChanged("SDTbn");
					this.OnSDTbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSkham", DbType="NVarChar(50)")]
		public string BSkham
		{
			get
			{
				return this._BSkham;
			}
			set
			{
				if ((this._BSkham != value))
				{
					this.OnBSkhamChanging(value);
					this.SendPropertyChanging();
					this._BSkham = value;
					this.SendPropertyChanged("BSkham");
					this.OnBSkhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tongtien", DbType="Float")]
		public System.Nullable<double> Tongtien
		{
			get
			{
				return this._Tongtien;
			}
			set
			{
				if ((this._Tongtien != value))
				{
					this.OnTongtienChanging(value);
					this.SendPropertyChanging();
					this._Tongtien = value;
					this.SendPropertyChanged("Tongtien");
					this.OnTongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaykham", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaykham
		{
			get
			{
				return this._Ngaykham;
			}
			set
			{
				if ((this._Ngaykham != value))
				{
					this.OnNgaykhamChanging(value);
					this.SendPropertyChanging();
					this._Ngaykham = value;
					this.SendPropertyChanged("Ngaykham");
					this.OnNgaykhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ToaThuoc_HoaDon", Storage="_ToaThuoc", ThisKey="IDtoa", OtherKey="IDtoa", IsForeignKey=true)]
		public ToaThuoc ToaThuoc
		{
			get
			{
				return this._ToaThuoc.Entity;
			}
			set
			{
				ToaThuoc previousValue = this._ToaThuoc.Entity;
				if (((previousValue != value) 
							|| (this._ToaThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ToaThuoc.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._ToaThuoc.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._IDtoa = value.IDtoa;
					}
					else
					{
						this._IDtoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("ToaThuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDnv;
		
		private string _Tennv;
		
		private string _SDTnv;
		
		private string _Diachinv;
		
		private string _Luong;
		
		private EntitySet<BenhNhan> _BenhNhans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDnvChanging(int value);
    partial void OnIDnvChanged();
    partial void OnTennvChanging(string value);
    partial void OnTennvChanged();
    partial void OnSDTnvChanging(string value);
    partial void OnSDTnvChanged();
    partial void OnDiachinvChanging(string value);
    partial void OnDiachinvChanged();
    partial void OnLuongChanging(string value);
    partial void OnLuongChanged();
    #endregion
		
		public NhanVien()
		{
			this._BenhNhans = new EntitySet<BenhNhan>(new Action<BenhNhan>(this.attach_BenhNhans), new Action<BenhNhan>(this.detach_BenhNhans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDnv", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDnv
		{
			get
			{
				return this._IDnv;
			}
			set
			{
				if ((this._IDnv != value))
				{
					this.OnIDnvChanging(value);
					this.SendPropertyChanging();
					this._IDnv = value;
					this.SendPropertyChanged("IDnv");
					this.OnIDnvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tennv", DbType="NVarChar(50)")]
		public string Tennv
		{
			get
			{
				return this._Tennv;
			}
			set
			{
				if ((this._Tennv != value))
				{
					this.OnTennvChanging(value);
					this.SendPropertyChanging();
					this._Tennv = value;
					this.SendPropertyChanged("Tennv");
					this.OnTennvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTnv", DbType="NVarChar(50)")]
		public string SDTnv
		{
			get
			{
				return this._SDTnv;
			}
			set
			{
				if ((this._SDTnv != value))
				{
					this.OnSDTnvChanging(value);
					this.SendPropertyChanging();
					this._SDTnv = value;
					this.SendPropertyChanged("SDTnv");
					this.OnSDTnvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachinv", DbType="NVarChar(50)")]
		public string Diachinv
		{
			get
			{
				return this._Diachinv;
			}
			set
			{
				if ((this._Diachinv != value))
				{
					this.OnDiachinvChanging(value);
					this.SendPropertyChanging();
					this._Diachinv = value;
					this.SendPropertyChanged("Diachinv");
					this.OnDiachinvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="NVarChar(50)")]
		public string Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_BenhNhan", Storage="_BenhNhans", ThisKey="IDnv", OtherKey="IDnv")]
		public EntitySet<BenhNhan> BenhNhans
		{
			get
			{
				return this._BenhNhans;
			}
			set
			{
				this._BenhNhans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BenhNhans(BenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_BenhNhans(BenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDthuoc;
		
		private string _Tenthuoc;
		
		private System.Nullable<double> _Soluong;
		
		private System.Nullable<double> _Gia;
		
		private string _Chucnang;
		
		private EntitySet<ThuocBenhNhan> _ThuocBenhNhans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDthuocChanging(int value);
    partial void OnIDthuocChanged();
    partial void OnTenthuocChanging(string value);
    partial void OnTenthuocChanged();
    partial void OnSoluongChanging(System.Nullable<double> value);
    partial void OnSoluongChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    partial void OnChucnangChanging(string value);
    partial void OnChucnangChanged();
    #endregion
		
		public Thuoc()
		{
			this._ThuocBenhNhans = new EntitySet<ThuocBenhNhan>(new Action<ThuocBenhNhan>(this.attach_ThuocBenhNhans), new Action<ThuocBenhNhan>(this.detach_ThuocBenhNhans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDthuoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDthuoc
		{
			get
			{
				return this._IDthuoc;
			}
			set
			{
				if ((this._IDthuoc != value))
				{
					this.OnIDthuocChanging(value);
					this.SendPropertyChanging();
					this._IDthuoc = value;
					this.SendPropertyChanged("IDthuoc");
					this.OnIDthuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenthuoc", DbType="NVarChar(50)")]
		public string Tenthuoc
		{
			get
			{
				return this._Tenthuoc;
			}
			set
			{
				if ((this._Tenthuoc != value))
				{
					this.OnTenthuocChanging(value);
					this.SendPropertyChanging();
					this._Tenthuoc = value;
					this.SendPropertyChanged("Tenthuoc");
					this.OnTenthuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Float")]
		public System.Nullable<double> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chucnang", DbType="NVarChar(50)")]
		public string Chucnang
		{
			get
			{
				return this._Chucnang;
			}
			set
			{
				if ((this._Chucnang != value))
				{
					this.OnChucnangChanging(value);
					this.SendPropertyChanging();
					this._Chucnang = value;
					this.SendPropertyChanged("Chucnang");
					this.OnChucnangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_ThuocBenhNhan", Storage="_ThuocBenhNhans", ThisKey="IDthuoc", OtherKey="IDthuoc")]
		public EntitySet<ThuocBenhNhan> ThuocBenhNhans
		{
			get
			{
				return this._ThuocBenhNhans;
			}
			set
			{
				this._ThuocBenhNhans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThuocBenhNhans(ThuocBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_ThuocBenhNhans(ThuocBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThuocBenhNhan")]
	public partial class ThuocBenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Tenthuoc;
		
		private System.Nullable<double> _Soluong;
		
		private System.Nullable<double> _Gia;
		
		private int _IDthuoc;
		
		private int _IDtoa;
		
		private EntityRef<Thuoc> _Thuoc;
		
		private EntityRef<ToaThuoc> _ToaThuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenthuocChanging(string value);
    partial void OnTenthuocChanged();
    partial void OnSoluongChanging(System.Nullable<double> value);
    partial void OnSoluongChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    partial void OnIDthuocChanging(int value);
    partial void OnIDthuocChanged();
    partial void OnIDtoaChanging(int value);
    partial void OnIDtoaChanged();
    #endregion
		
		public ThuocBenhNhan()
		{
			this._Thuoc = default(EntityRef<Thuoc>);
			this._ToaThuoc = default(EntityRef<ToaThuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenthuoc", DbType="NVarChar(50)")]
		public string Tenthuoc
		{
			get
			{
				return this._Tenthuoc;
			}
			set
			{
				if ((this._Tenthuoc != value))
				{
					this.OnTenthuocChanging(value);
					this.SendPropertyChanging();
					this._Tenthuoc = value;
					this.SendPropertyChanged("Tenthuoc");
					this.OnTenthuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Float")]
		public System.Nullable<double> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDthuoc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDthuoc
		{
			get
			{
				return this._IDthuoc;
			}
			set
			{
				if ((this._IDthuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDthuocChanging(value);
					this.SendPropertyChanging();
					this._IDthuoc = value;
					this.SendPropertyChanged("IDthuoc");
					this.OnIDthuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDtoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDtoa
		{
			get
			{
				return this._IDtoa;
			}
			set
			{
				if ((this._IDtoa != value))
				{
					if (this._ToaThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDtoaChanging(value);
					this.SendPropertyChanging();
					this._IDtoa = value;
					this.SendPropertyChanged("IDtoa");
					this.OnIDtoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_ThuocBenhNhan", Storage="_Thuoc", ThisKey="IDthuoc", OtherKey="IDthuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.ThuocBenhNhans.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.ThuocBenhNhans.Add(this);
						this._IDthuoc = value.IDthuoc;
					}
					else
					{
						this._IDthuoc = default(int);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ToaThuoc_ThuocBenhNhan", Storage="_ToaThuoc", ThisKey="IDtoa", OtherKey="IDtoa", IsForeignKey=true)]
		public ToaThuoc ToaThuoc
		{
			get
			{
				return this._ToaThuoc.Entity;
			}
			set
			{
				ToaThuoc previousValue = this._ToaThuoc.Entity;
				if (((previousValue != value) 
							|| (this._ToaThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ToaThuoc.Entity = null;
						previousValue.ThuocBenhNhans.Remove(this);
					}
					this._ToaThuoc.Entity = value;
					if ((value != null))
					{
						value.ThuocBenhNhans.Add(this);
						this._IDtoa = value.IDtoa;
					}
					else
					{
						this._IDtoa = default(int);
					}
					this.SendPropertyChanged("ToaThuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ToaThuoc")]
	public partial class ToaThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDtoa;
		
		private string _Tenbn;
		
		private string _SDTbn;
		
		private string _Benh;
		
		private string _BSkham;
		
		private System.Nullable<int> _IDdsbn;
		
		private string _Thanhtoan;
		
		private System.Nullable<System.DateTime> _Ngaykham;
		
		private EntitySet<BenhAn> _BenhAns;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<ThuocBenhNhan> _ThuocBenhNhans;
		
		private EntityRef<DanhSachBenhNhan> _DanhSachBenhNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDtoaChanging(int value);
    partial void OnIDtoaChanged();
    partial void OnTenbnChanging(string value);
    partial void OnTenbnChanged();
    partial void OnSDTbnChanging(string value);
    partial void OnSDTbnChanged();
    partial void OnBenhChanging(string value);
    partial void OnBenhChanged();
    partial void OnBSkhamChanging(string value);
    partial void OnBSkhamChanged();
    partial void OnIDdsbnChanging(System.Nullable<int> value);
    partial void OnIDdsbnChanged();
    partial void OnThanhtoanChanging(string value);
    partial void OnThanhtoanChanged();
    partial void OnNgaykhamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaykhamChanged();
    #endregion
		
		public ToaThuoc()
		{
			this._BenhAns = new EntitySet<BenhAn>(new Action<BenhAn>(this.attach_BenhAns), new Action<BenhAn>(this.detach_BenhAns));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._ThuocBenhNhans = new EntitySet<ThuocBenhNhan>(new Action<ThuocBenhNhan>(this.attach_ThuocBenhNhans), new Action<ThuocBenhNhan>(this.detach_ThuocBenhNhans));
			this._DanhSachBenhNhan = default(EntityRef<DanhSachBenhNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDtoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDtoa
		{
			get
			{
				return this._IDtoa;
			}
			set
			{
				if ((this._IDtoa != value))
				{
					this.OnIDtoaChanging(value);
					this.SendPropertyChanging();
					this._IDtoa = value;
					this.SendPropertyChanged("IDtoa");
					this.OnIDtoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenbn", DbType="NVarChar(50)")]
		public string Tenbn
		{
			get
			{
				return this._Tenbn;
			}
			set
			{
				if ((this._Tenbn != value))
				{
					this.OnTenbnChanging(value);
					this.SendPropertyChanging();
					this._Tenbn = value;
					this.SendPropertyChanged("Tenbn");
					this.OnTenbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTbn", DbType="NVarChar(50)")]
		public string SDTbn
		{
			get
			{
				return this._SDTbn;
			}
			set
			{
				if ((this._SDTbn != value))
				{
					this.OnSDTbnChanging(value);
					this.SendPropertyChanging();
					this._SDTbn = value;
					this.SendPropertyChanged("SDTbn");
					this.OnSDTbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Benh", DbType="NVarChar(50)")]
		public string Benh
		{
			get
			{
				return this._Benh;
			}
			set
			{
				if ((this._Benh != value))
				{
					this.OnBenhChanging(value);
					this.SendPropertyChanging();
					this._Benh = value;
					this.SendPropertyChanged("Benh");
					this.OnBenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSkham", DbType="NVarChar(50)")]
		public string BSkham
		{
			get
			{
				return this._BSkham;
			}
			set
			{
				if ((this._BSkham != value))
				{
					this.OnBSkhamChanging(value);
					this.SendPropertyChanging();
					this._BSkham = value;
					this.SendPropertyChanged("BSkham");
					this.OnBSkhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDdsbn", DbType="Int")]
		public System.Nullable<int> IDdsbn
		{
			get
			{
				return this._IDdsbn;
			}
			set
			{
				if ((this._IDdsbn != value))
				{
					if (this._DanhSachBenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDdsbnChanging(value);
					this.SendPropertyChanging();
					this._IDdsbn = value;
					this.SendPropertyChanged("IDdsbn");
					this.OnIDdsbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanhtoan", DbType="NVarChar(50)")]
		public string Thanhtoan
		{
			get
			{
				return this._Thanhtoan;
			}
			set
			{
				if ((this._Thanhtoan != value))
				{
					this.OnThanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Thanhtoan = value;
					this.SendPropertyChanged("Thanhtoan");
					this.OnThanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaykham", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaykham
		{
			get
			{
				return this._Ngaykham;
			}
			set
			{
				if ((this._Ngaykham != value))
				{
					this.OnNgaykhamChanging(value);
					this.SendPropertyChanging();
					this._Ngaykham = value;
					this.SendPropertyChanged("Ngaykham");
					this.OnNgaykhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ToaThuoc_BenhAn", Storage="_BenhAns", ThisKey="IDtoa", OtherKey="IDtoa")]
		public EntitySet<BenhAn> BenhAns
		{
			get
			{
				return this._BenhAns;
			}
			set
			{
				this._BenhAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ToaThuoc_HoaDon", Storage="_HoaDons", ThisKey="IDtoa", OtherKey="IDtoa")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ToaThuoc_ThuocBenhNhan", Storage="_ThuocBenhNhans", ThisKey="IDtoa", OtherKey="IDtoa")]
		public EntitySet<ThuocBenhNhan> ThuocBenhNhans
		{
			get
			{
				return this._ThuocBenhNhans;
			}
			set
			{
				this._ThuocBenhNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachBenhNhan_ToaThuoc", Storage="_DanhSachBenhNhan", ThisKey="IDdsbn", OtherKey="IDdsbn", IsForeignKey=true)]
		public DanhSachBenhNhan DanhSachBenhNhan
		{
			get
			{
				return this._DanhSachBenhNhan.Entity;
			}
			set
			{
				DanhSachBenhNhan previousValue = this._DanhSachBenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._DanhSachBenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhSachBenhNhan.Entity = null;
						previousValue.ToaThuocs.Remove(this);
					}
					this._DanhSachBenhNhan.Entity = value;
					if ((value != null))
					{
						value.ToaThuocs.Add(this);
						this._IDdsbn = value.IDdsbn;
					}
					else
					{
						this._IDdsbn = default(Nullable<int>);
					}
					this.SendPropertyChanged("DanhSachBenhNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BenhAns(BenhAn entity)
		{
			this.SendPropertyChanging();
			entity.ToaThuoc = this;
		}
		
		private void detach_BenhAns(BenhAn entity)
		{
			this.SendPropertyChanging();
			entity.ToaThuoc = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ToaThuoc = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ToaThuoc = null;
		}
		
		private void attach_ThuocBenhNhans(ThuocBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.ToaThuoc = this;
		}
		
		private void detach_ThuocBenhNhans(ThuocBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.ToaThuoc = null;
		}
	}
}
#pragma warning restore 1591
